/**
 * Installing the compatibility preamble into an extension's own copy.
 *
 * Electron compiles out several `chrome.*` namespaces even when an extension
 * declares the permission, and an extension's service worker has no other
 * injection point: `ses.registerPreloadScript({ type: 'service-worker' })`
 * registers and is listed but the worker never sees the script (measured against
 * the shipped runtime). The file the worker executes is the only route in, so the
 * preamble is written into the copy the app owns and the entry is pointed at it.
 *
 * Two shapes, because a module worker evaluates its hoisted `import`s before any
 * statement in its own body, so prepending to a module body would run too late for
 * a polyfill that reads `chrome` at import time:
 *
 *   - **module worker**: a generated bootstrap module imports the preamble first
 *     and the original entry second, and `background.service_worker` is repointed
 *     at it. The extension's own files are left untouched.
 *   - **classic worker**: the preamble is prepended to the entry file. A bootstrap
 *     using `importScripts` would move the worker's script URL and break every
 *     relative `importScripts` inside the original, so prepending is the only safe
 *     shape. The preamble ends with a semicolon, which matters: a body that starts
 *     with `(` would otherwise be swallowed by automatic semicolon insertion into
 *     `preamble()(body)()` and the worker would die on its first line.
 *
 * MV2 extensions with a `background.scripts` array get the classic prepend, since
 * that is the same shape. MV2 is not promised, only made to work if the user
 * installs one from a folder.
 */

import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { BrowserExtensionInjection } from '../../../lib/ipc/browser'

export const COMPAT_PREAMBLE_FILE_NAME = 'cio-compat-preamble.js'
export const COMPAT_BOOTSTRAP_FILE_NAME = 'cio-compat-bootstrap.js'

/** Marked in the generated bootstrap so a re-install can tell its own output from
 *  an extension's file. */
const GENERATED_FILE_BANNER =
  '/* Generated by CodeInOven at install time. Do not edit; reinstalling rewrites it. */'

export interface InjectionOutcome {
  injection: BrowserExtensionInjection
  /** Extension-root-relative entry the preamble was installed for, or null when
   *  the extension declares no background at all. */
  entry: string | null
}

function asRecord(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {}
}

/** Extension-root-relative form of a manifest path, so `join` cannot leave the
 *  extension's own folder. */
function relativeEntryPath(declared: string): string {
  return declared.replace(/^\/+/u, '')
}

function isCompatibleEntry(declared: string, extensionDir: string): boolean {
  return existsSync(join(extensionDir, relativeEntryPath(declared)))
}

/** Whether a file already carries the preamble, so a folder that was itself once
 *  installed by this app is not injected twice. */
function alreadyPreamble(contents: string): boolean {
  return contents.includes('__cioCompat') && contents.includes('CIO compatibility preamble')
}

/**
 * Install the preamble into `extensionDir`, mutating `manifest`'s background
 * declaration in place. The caller writes the manifest, so a manifest is written
 * exactly once per install no matter how many things changed in it.
 */
export async function injectCompatibilityPreamble(
  extensionDir: string,
  manifest: Record<string, unknown>,
  preambleSource: string
): Promise<InjectionOutcome> {
  const background = asRecord(manifest['background'])
  const serviceWorker = background['service_worker']
  const scripts = Array.isArray(background['scripts']) ? background['scripts'] : []

  if (typeof serviceWorker === 'string' && serviceWorker.length > 0) {
    if (!isCompatibleEntry(serviceWorker, extensionDir)) {
      throw new Error(`The extension declares a background worker that is not in the package (${serviceWorker})`)
    }
    const entry = relativeEntryPath(serviceWorker)
    if (background['type'] === 'module') {
      await writeFile(join(extensionDir, COMPAT_PREAMBLE_FILE_NAME), `${preambleSource}\n`)
      await writeFile(
        join(extensionDir, COMPAT_BOOTSTRAP_FILE_NAME),
        [
          GENERATED_FILE_BANNER,
          `import './${COMPAT_PREAMBLE_FILE_NAME}'`,
          `import './${entry}'`,
          ''
        ].join('\n')
      )
      background['service_worker'] = COMPAT_BOOTSTRAP_FILE_NAME
      manifest['background'] = background
      return { injection: 'module-bootstrap', entry }
    }
    const absolute = join(extensionDir, entry)
    const original = await readFile(absolute, 'utf8')
    if (!alreadyPreamble(original)) {
      await writeFile(absolute, `${preambleSource}\n${original}`)
    }
    return { injection: 'prepend-classic', entry }
  }

  const firstScript = scripts.find((candidate): candidate is string => typeof candidate === 'string')
  if (firstScript) {
    if (!isCompatibleEntry(firstScript, extensionDir)) {
      throw new Error(
        `The extension declares a background script that is not in the package (${firstScript})`
      )
    }
    const entry = relativeEntryPath(firstScript)
    const absolute = join(extensionDir, entry)
    const original = await readFile(absolute, 'utf8')
    if (!alreadyPreamble(original)) {
      await writeFile(absolute, `${preambleSource}\n${original}`)
    }
    return { injection: 'prepend-mv2', entry }
  }

  // No background of any kind is legitimate: a content-script-only or
  // popup-only extension has nothing to inject into.
  return { injection: 'none', entry: null }
}
