/**
 * Installing the compatibility preamble into an extension's own copy.
 *
 * Electron compiles out several `chrome.*` namespaces even when an extension
 * declares the permission, and an extension's service worker has no other
 * injection point: `ses.registerPreloadScript({ type: 'service-worker' })`
 * registers and is listed but the worker never sees the script (measured against
 * the shipped runtime). The file the worker executes is the only route in, so the
 * preamble is written into the copy the app owns and the entry is pointed at it.
 *
 * Two shapes, because a module worker evaluates its hoisted `import`s before any
 * statement in its own body, so prepending to a module body would run too late for
 * a polyfill that reads `chrome` at import time:
 *
 *   - **module worker**: a generated bootstrap module imports the preamble first
 *     and the original entry second, and `background.service_worker` is repointed
 *     at it. The extension's own files are left untouched.
 *   - **classic worker**: the preamble is prepended to the entry file. A bootstrap
 *     using `importScripts` would move the worker's script URL and break every
 *     relative `importScripts` inside the original, so prepending is the only safe
 *     shape. The preamble ends with a semicolon, which matters: a body that starts
 *     with `(` would otherwise be swallowed by automatic semicolon insertion into
 *     `preamble()(body)()` and the worker would die on its first line.
 *
 * MV2 extensions with a `background.scripts` array get the classic prepend, since
 * that is the same shape. MV2 is not promised, only made to work if the user
 * installs one from a folder.
 */

/// <reference types="vite/client" />
import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { BrowserExtensionInjection } from '../../../lib/ipc/browser'
import bridgePageSource from './compat/cio-bridge.page.html?raw'
import bridgeScriptSource from './compat/cio-bridge.js?raw'

export const COMPAT_PREAMBLE_FILE_NAME = 'cio-compat-preamble.js'
export const COMPAT_BOOTSTRAP_FILE_NAME = 'cio-compat-bootstrap.js'
export const COMPAT_BRIDGE_PAGE_FILE_NAME = 'cio-bridge.html'
export const COMPAT_BRIDGE_SCRIPT_FILE_NAME = 'cio-bridge.js'

/** Marked in the generated bootstrap so a re-install can tell its own output from
 *  an extension's file. */
const GENERATED_FILE_BANNER =
  '/* Generated by CodeInOven at install time. Do not edit; reinstalling rewrites it. */'

/** Opening words of the preamble's own banner, used to find the block in a copy
 *  whose sidecar is missing (installed before the sidecar existed). */
const PREAMBLE_START_MARKER = 'CIO compatibility preamble for a browser box extension'

/** The preamble's own last line, written by the preamble file itself. Splitting on
 *  it is what makes rewriting a stale block exact instead of heuristic. */
const PREAMBLE_END_MARKER = '// ── CIO compatibility preamble ends here'

/** The exact text a classic prepend puts in front of an entry file. Also the
 *  content of the sidecar, so one string describes both shapes.
 *
 *  The block has to terminate its own last statement, because the file it is
 *  prepended to is outside this file's view: a body that begins with `(` (Bitwarden's
 *  does) would otherwise be parsed as a call on whatever the block returned. The
 *  terminator is added here rather than trusted to the preamble's own formatting,
 *  where a formatter may drop it. */
function prependedPreamble(preambleSource: string): string {
  return `${preambleSource.replace(/\s+$/u, '')}\n;\n`
}

/** Write `contents` only when the file does not already hold them, so refreshing
 *  an installed copy does not touch mtimes or disk for no change. */
async function writeIfChanged(path: string, contents: string): Promise<void> {
  const current = await readFile(path, 'utf8').catch(() => null)
  if (current === contents) return
  await writeFile(path, contents)
}

/**
 * Write the bridge page the app drives into the extension's own copy.
 *
 * The page is what carries tab lifecycle events into the worker and action state
 * back out (see `browser-extension-bridge.ts`). It is the app's own file, never
 * the extension's, so an update can rewrite it in an installed copy the same way
 * `ensureInjectionCurrent` rewrites a stale preamble.
 */
async function writeBridgeFiles(extensionDir: string): Promise<void> {
  await writeIfChanged(join(extensionDir, COMPAT_BRIDGE_PAGE_FILE_NAME), bridgePageSource)
  await writeIfChanged(join(extensionDir, COMPAT_BRIDGE_SCRIPT_FILE_NAME), bridgeScriptSource)
}

/**
 * Where a previously installed preamble block ends inside `contents`.
 *
 * The end marker is exact. A copy installed before that marker existed falls back
 * to the preamble being a single IIFE, so its end is the first closing line after
 * the banner, and the result is only accepted when the block it produces really
 * holds our own state object.
 */
function preambleBlockEnd(contents: string): number | null {
  const marked = contents.indexOf(PREAMBLE_END_MARKER)
  if (marked !== -1) {
    let end = contents.indexOf('\n', marked)
    end = end === -1 ? contents.length : end + 1
    // The prepend's own terminator sits on the line after the block, so it is
    // consumed with the block instead of being left in front of the extension.
    for (;;) {
      const line = contents.slice(end).split('\n', 1)[0]
      if (line.trim() !== '' && line.trim() !== ';') break
      if (!contents.slice(end).includes('\n')) break
      end += line.length + 1
    }
    return end
  }
  const banner = contents.indexOf(PREAMBLE_START_MARKER)
  if (banner === -1) return null
  const closing = contents.indexOf('\n})();\n', banner)
  if (closing === -1) return null
  const end = closing + '\n})();\n'.length
  return contents.slice(0, end).includes('__cioCompat') ? end : null
}

export interface InjectionOutcome {
  injection: BrowserExtensionInjection
  /** Extension-root-relative entry the preamble was installed for, or null when
   *  the extension declares no background at all. */
  entry: string | null
}

function asRecord(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {}
}

/** Extension-root-relative form of a manifest path, so `join` cannot leave the
 *  extension's own folder. */
function relativeEntryPath(declared: string): string {
  return declared.replace(/^\/+/u, '')
}

function isCompatibleEntry(declared: string, extensionDir: string): boolean {
  return existsSync(join(extensionDir, relativeEntryPath(declared)))
}

/** Whether a file already carries the preamble, so a folder that was itself once
 *  installed by this app is not injected twice. */
function alreadyPreamble(contents: string): boolean {
  return contents.includes('__cioCompat') && contents.includes('CIO compatibility preamble')
}

/**
 * Install the preamble into `extensionDir`, mutating `manifest`'s background
 * declaration in place. The caller writes the manifest, so a manifest is written
 * exactly once per install no matter how many things changed in it.
 */
export async function injectCompatibilityPreamble(
  extensionDir: string,
  manifest: Record<string, unknown>,
  preambleSource: string
): Promise<InjectionOutcome> {
  const background = asRecord(manifest['background'])
  const serviceWorker = background['service_worker']
  const scripts = Array.isArray(background['scripts']) ? background['scripts'] : []

  if (typeof serviceWorker === 'string' && serviceWorker.length > 0) {
    if (!isCompatibleEntry(serviceWorker, extensionDir)) {
      throw new Error(
        `The extension declares a background worker that is not in the package (${serviceWorker})`
      )
    }
    const entry = relativeEntryPath(serviceWorker)
    if (background['type'] === 'module') {
      await writeFile(
        join(extensionDir, COMPAT_PREAMBLE_FILE_NAME),
        prependedPreamble(preambleSource)
      )
      await writeFile(
        join(extensionDir, COMPAT_BOOTSTRAP_FILE_NAME),
        [
          GENERATED_FILE_BANNER,
          `import './${COMPAT_PREAMBLE_FILE_NAME}'`,
          `import './${entry}'`,
          ''
        ].join('\n')
      )
      background['service_worker'] = COMPAT_BOOTSTRAP_FILE_NAME
      manifest['background'] = background
      await writeBridgeFiles(extensionDir)
      return { injection: 'module-bootstrap', entry }
    }
    const absolute = join(extensionDir, entry)
    const original = await readFile(absolute, 'utf8')
    if (!alreadyPreamble(original)) {
      await writeFile(absolute, `${prependedPreamble(preambleSource)}${original}`)
      await writeFile(
        join(extensionDir, COMPAT_PREAMBLE_FILE_NAME),
        prependedPreamble(preambleSource)
      )
    }
    await writeBridgeFiles(extensionDir)
    return { injection: 'prepend-classic', entry }
  }

  const firstScript = scripts.find(
    (candidate): candidate is string => typeof candidate === 'string'
  )
  if (firstScript) {
    if (!isCompatibleEntry(firstScript, extensionDir)) {
      throw new Error(
        `The extension declares a background script that is not in the package (${firstScript})`
      )
    }
    const entry = relativeEntryPath(firstScript)
    const absolute = join(extensionDir, entry)
    const original = await readFile(absolute, 'utf8')
    if (!alreadyPreamble(original)) {
      await writeFile(absolute, `${prependedPreamble(preambleSource)}${original}`)
      await writeFile(
        join(extensionDir, COMPAT_PREAMBLE_FILE_NAME),
        prependedPreamble(preambleSource)
      )
    }
    await writeBridgeFiles(extensionDir)
    return { injection: 'prepend-mv2', entry }
  }

  // No background of any kind is legitimate: a content-script-only or
  // popup-only extension has nothing to inject into.
  return { injection: 'none', entry: null }
}

/** What refreshing an installed copy did, or could not do. */
export type InjectionRefresh = 'current' | 'rewritten' | 'none' | 'unknown'

/**
 * Bring an already installed copy up to the current preamble.
 *
 * The preamble is code the app ships, and the copy on disk is a prepend (classic
 * worker) or a generated import (module worker) once written. An app update that
 * changes the preamble therefore has to reach extensions that are already
 * installed, or a fix in it only ever applies to extensions installed afterwards.
 *
 * The sidecar written next to the copy is what makes the swap exact: it holds the
 * text that was prepended, so the entry can be split at a known length. A copy
 * installed before the sidecar existed is split on the preamble's own end marker
 * instead (see `preambleBlockEnd`). Rewriting never touches the extension's own
 * code, which is what keeps the extension id and its stored data valid.
 */
export async function ensureInjectionCurrent(
  extensionDir: string,
  manifest: Record<string, unknown>,
  preambleSource: string
): Promise<InjectionRefresh> {
  const background = asRecord(manifest['background'])
  const serviceWorker = background['service_worker']
  const scripts = Array.isArray(background['scripts']) ? background['scripts'] : []
  const declared =
    typeof serviceWorker === 'string' && serviceWorker.length > 0
      ? serviceWorker
      : scripts.find((candidate): candidate is string => typeof candidate === 'string')
  if (!declared) return 'none'

  // The bridge page travels with the preamble: a copy installed before it existed
  // gets it here, and an app update reaches both files the same way.
  await writeBridgeFiles(extensionDir)

  const current = prependedPreamble(preambleSource)
  const sidecar = join(extensionDir, COMPAT_PREAMBLE_FILE_NAME)

  const installed = await readFile(sidecar, 'utf8').catch(() => null)
  if (installed === current) return 'current'

  // The generated bootstrap imports the sidecar, so the manifest already points at
  // the preamble and only the imported file has to move.
  if (relativeEntryPath(declared) === COMPAT_BOOTSTRAP_FILE_NAME) {
    if (installed === null) return 'unknown'
    await writeFile(sidecar, current)
    return 'rewritten'
  }

  const absolute = join(extensionDir, relativeEntryPath(declared))
  const contents = await readFile(absolute, 'utf8').catch(() => null)
  if (contents === null || !alreadyPreamble(contents)) return 'none'

  if (installed !== null && contents.startsWith(installed)) {
    const body = contents.slice(installed.length)
    if (body.length === 0) return 'unknown'
    await writeFile(absolute, `${current}${body}`)
    await writeFile(sidecar, current)
    return 'rewritten'
  }

  const end = preambleBlockEnd(contents)
  if (end === null) return 'unknown'
  // A copy written by the older prepend carries the separator line the prepend
  // added, which the current write does not: without trimming it every upgrade
  // leaves one more blank line in front of the extension's code.
  const rest = contents.slice(end)
  const body = rest.startsWith('\n') ? rest.slice(1) : rest
  if (body.length === 0) return 'unknown'
  await writeFile(absolute, `${current}${body}`)
  await writeFile(sidecar, current)
  return 'rewritten'
}
