import type { AgentTokenUsage } from '$shared/types'

/**
 * Tokens-per-second display helpers.
 *
 * Harnesses that report a native generation rate are echoed through the same
 * formatting; harnesses that only report cumulative token counts get the rate
 * derived here from those counts and wall-clock time. A harness reporting
 * neither is simply exempt — every entry point returns `null` and the UI
 * omits the segment.
 */

/** Tokens actually generated by the model (output plus visible reasoning). */
export function generatedTokens(tokens?: AgentTokenUsage | null): number {
  if (!tokens) return 0
  return Math.max(0, tokens.output ?? 0) + Math.max(0, tokens.reasoning ?? 0)
}

/** Formats a generation rate as e.g. `40 tok/s` (grouped: `1,234 tok/s`). */
export function formatTokenRate(tokensPerSecond: number): string {
  return `${Math.max(1, Math.round(tokensPerSecond)).toLocaleString()} tok/s`
}

/**
 * Tracks the cumulative generated tokens of the live assistant message to
 * derive a live tokens-per-second rate. The clock starts when the first
 * non-zero token report arrives for a message; observing a different message
 * id resets the window, so consecutive turns never share a baseline.
 */
export class LiveTokenRate {
  #messageId = $state<string | null>(null)
  #tokens = $state(0)
  #startedAt = $state(0)
  #now = $state(0)
  #timer: ReturnType<typeof setInterval> | null = null

  get messageId(): string | null {
    return this.#messageId
  }

  /** Feed one cumulative token report for the message currently streaming. */
  observe(messageId: string, tokens?: AgentTokenUsage | null): void {
    const generated = generatedTokens(tokens)
    if (generated <= 0) return
    if (this.#messageId !== messageId) {
      this.#messageId = messageId
      this.#tokens = generated
      this.#startedAt = Date.now()
    } else {
      // Token counters are cumulative per turn; never regress on a reordered
      // or partial report.
      this.#tokens = Math.max(this.#tokens, generated)
    }
    this.#now = Date.now()
    if (!this.#timer) {
      this.#timer = setInterval(() => {
        this.#now = Date.now()
      }, 1000)
    }
  }

  /** Final rate for the observed message, or `null` when nothing was observed. */
  finalize(): number | null {
    const rate = this.rate()
    this.clear()
    return rate
  }

  clear(): void {
    if (this.#timer) {
      clearInterval(this.#timer)
      this.#timer = null
    }
    this.#messageId = null
    this.#tokens = 0
    this.#startedAt = 0
    this.#now = 0
  }

  /** Current live rate, or `null` before the first token report. Reactive:
   *  recomputes once per second while the internal clock ticks. */
  rate(): number | null {
    if (!this.#messageId || this.#tokens <= 0 || this.#startedAt <= 0) return null
    void this.#now
    const seconds = (this.#now - this.#startedAt) / 1000
    if (seconds <= 0) return null
    return this.#tokens / seconds
  }
}
