import type { AgentTokenUsage } from '$shared/types'

/**
 * Tokens-per-second display helpers.
 *
 * Harnesses that report a native generation rate are echoed through the same
 * formatting; harnesses that only report cumulative token counts get the rate
 * derived here from those counts and wall-clock time. A harness reporting
 * neither is simply exempt — every entry point returns `null` and the UI
 * omits the segment.
 */

/** Tokens actually generated by the model (output plus visible reasoning). */
export function generatedTokens(tokens?: AgentTokenUsage | null): number {
  if (!tokens) return 0
  return Math.max(0, tokens.output ?? 0) + Math.max(0, tokens.reasoning ?? 0)
}

/** Rough tokens-per-character divisor for streamed-text estimation. */
const CHARS_PER_TOKEN = 4

/**
 * Estimates generated tokens from streamed text/reasoning parts while the
 * harness reports no usage during a turn. Approximate (~4 chars/token) — it
 * only powers the live indicator until a real usage report arrives.
 */
export function estimateGeneratedTokens(parts: readonly { type: string; text?: string }[]): number {
  let chars = 0
  for (const part of parts) {
    if ((part.type === 'text' || part.type === 'reasoning') && part.text) chars += part.text.length
  }
  return Math.round(chars / CHARS_PER_TOKEN)
}

/** Formats a generation rate as e.g. `40 tok/s` (grouped: `1,234 tok/s`). */
export function formatTokenRate(tokensPerSecond: number): string {
  return `${Math.max(1, Math.round(tokensPerSecond)).toLocaleString()} tok/s`
}

/**
 * Tracks the cumulative generated tokens of the live assistant message to
 * derive a live tokens-per-second rate. The clock starts when the first
 * non-zero token report arrives for a message; observing a different message
 * id resets the window, so consecutive turns never share a baseline.
 */
export class LiveTokenRate {
  #messageId = $state<string | null>(null)
  #tokens = $state(0)
  #startedAt = $state(0)
  #now = $state(0)
  /** True while the window's token counts are stream-derived estimates rather
   *  than harness-reported usage. Real reports always take precedence. */
  #estimated = $state(false)
  #timer: ReturnType<typeof setInterval> | null = null

  get messageId(): string | null {
    return this.#messageId
  }

  /** Feed one cumulative generated-token count for the message currently
   *  streaming. Estimated counts (derived from streamed text while the
   *  harness reports no usage) never override a real report. */
  observe(messageId: string, generated: number, estimated = false): void {
    if (generated <= 0) return
    if (this.#messageId !== messageId) {
      this.#messageId = messageId
      this.#tokens = generated
      this.#startedAt = Date.now()
      this.#estimated = estimated
    } else {
      if (estimated && !this.#estimated) return
      if (!estimated && this.#estimated) {
        // A real report replaces the estimate wholesale: estimation bases and
        // reported bases are not comparable.
        this.#tokens = generated
        this.#estimated = false
        this.#now = Date.now()
        return
      }
      // Token counters are cumulative per turn; never regress on a reordered
      // or partial report.
      this.#tokens = Math.max(this.#tokens, generated)
    }
    this.#now = Date.now()
    if (!this.#timer) {
      this.#timer = setInterval(() => {
        this.#now = Date.now()
      }, 1000)
    }
  }

  /** Final rate for the observed message, or `null` when nothing was observed. */
  finalize(): number | null {
    const rate = this.rate()
    this.clear()
    return rate
  }

  clear(): void {
    if (this.#timer) {
      clearInterval(this.#timer)
      this.#timer = null
    }
    this.#messageId = null
    this.#tokens = 0
    this.#startedAt = 0
    this.#now = 0
    this.#estimated = false
  }

  /** Current live rate, or `null` before the first token report. Reactive:
   *  recomputes once per second while the internal clock ticks. */
  rate(): number | null {
    if (!this.#messageId || this.#tokens <= 0 || this.#startedAt <= 0) return null
    void this.#now
    const seconds = (this.#now - this.#startedAt) / 1000
    if (seconds <= 0) return null
    return this.#tokens / seconds
  }
}
