/**
 * Keeping the Oven service alive on Windows without a console window.
 *
 * A console program a Windows shell starts owns a visible window, and OpenSSH
 * there ends the whole process tree when the session closes, so a plain spawn
 * both flashes a window and dies with the connection. A scheduled task fixes
 * both: the Task Scheduler service owns the process rather than the SSH session,
 * and the task runs a `.vbs` whose `Run` uses window style 0, so `wscript.exe`
 * (a GUI-subsystem host with no console of its own) starts node hidden. The same
 * task is what brings the service back after a reboot.
 *
 * This module is deliberately free of Electron so the published `cio-oven` CLI
 * can control the very same task the desktop app installs. It only builds the
 * scripts and drives `schtasks`; nothing here runs on a non-Windows machine.
 */
import { spawn } from 'node:child_process'

/** The one task name every data root shares, so a machine has one Oven service. */
export const WINDOWS_TASK_NAME = 'CodeInOven Oven'
/** Home of the hidden launcher the task runs. */
export const WINDOWS_LAUNCHER_FILE = 'service-launch.vbs'
/** The launcher an earlier release wrote and started through cmd.exe. */
const LEGACY_LAUNCHER_FILE = 'service-start.cmd'

export interface WindowsLauncherInput {
  /** Absolute path to `node.exe`. */
  nodePath: string
  /** Absolute path to the deployed `service.mjs`. */
  servicePath: string
  /** Data root the daemon reads and writes. */
  dataRoot: string
  /** Service revision to report, so the app can match its own build. */
  revision?: string
}

/** Quote a value as a VBScript string literal. */
function vbs(value: string): string {
  if (value.includes('\0'))
    throw new TypeError('A Windows launcher path cannot contain null bytes.')
  return `"${value.replace(/"/gu, '""')}"`
}

/**
 * The hidden launcher.
 *
 * Environment is set on the launcher process so `node` inherits exactly what the
 * direct launch would have passed: the data root, the revision, and a `PATH`
 * that puts the shipped Node beside any other.
 */
export function windowsLauncherScript(input: WindowsLauncherInput): string {
  const nodeDirectory = input.nodePath.replace(/[\\/][^\\/]+$/u, '')
  const lines = [
    "' CodeInOven Oven service launcher. Generated by CodeInOven; do not edit.",
    'Set shell = CreateObject("WScript.Shell")',
    `shell.Environment("PROCESS")("CODEINOVEN_OVEN_DATA_ROOT") = ${vbs(input.dataRoot)}`,
    ...(input.revision
      ? [`shell.Environment("PROCESS")("CODEINOVEN_OVEN_REVISION") = ${vbs(input.revision)}`]
      : []),
    `shell.Environment("PROCESS")("PATH") = ${vbs(`${nodeDirectory};`)} & shell.Environment("PROCESS")("PATH")`,
    `shell.Run ${vbs(`"${input.nodePath}" "${input.servicePath}" daemon`)}, 0, False`
  ]
  return `${lines.join('\r\n')}\r\n`
}

/** The command script a previous release used; removed on the way to the task. */
export function legacyWindowsLauncherFile(): string {
  return LEGACY_LAUNCHER_FILE
}

/**
 * The task's action.
 *
 * `wscript.exe //B` runs the launcher in batch mode, suppressing its own error
 * dialogs, and the `.vbs` decides the window style. Naming `wscript` explicitly
 * rather than relying on the `.vbs` association means a machine that reassigned
 * it still starts the service.
 */
export function windowsTaskAction(launcherPath: string): string {
  return `wscript.exe //B //NoLogo "${launcherPath}"`
}

/** Create the logon task, replacing any earlier copy of it. */
export function registerTaskArgs(launcherPath: string): string[] {
  return [
    '/Create',
    '/SC',
    'ONLOGON',
    '/TR',
    windowsTaskAction(launcherPath),
    '/F',
    '/TN',
    WINDOWS_TASK_NAME
  ]
}

export function runTaskArgs(): string[] {
  return ['/Run', '/TN', WINDOWS_TASK_NAME]
}

export function enableTaskArgs(): string[] {
  return ['/Change', '/TN', WINDOWS_TASK_NAME, '/ENABLE']
}

export function disableTaskArgs(): string[] {
  return ['/Change', '/TN', WINDOWS_TASK_NAME, '/DISABLE']
}

export function endTaskArgs(): string[] {
  return ['/End', '/TN', WINDOWS_TASK_NAME]
}

export function deleteTaskArgs(): string[] {
  return ['/Delete', '/TN', WINDOWS_TASK_NAME, '/F']
}

/** Run one `schtasks` command, resolving to its exit code; never throws. */
export function runSchtasks(args: string[], timeoutMs = 20_000): Promise<number> {
  return new Promise((resolve) => {
    let settled = false
    const finish = (code: number): void => {
      if (settled) return
      settled = true
      resolve(code)
    }
    let child
    try {
      child = spawn('schtasks.exe', args, { stdio: 'ignore', windowsHide: true })
    } catch {
      finish(-1)
      return
    }
    const timer = setTimeout(() => {
      child.kill()
      finish(-1)
    }, timeoutMs)
    child.once('error', () => {
      clearTimeout(timer)
      finish(-1)
    })
    child.once('close', (code) => {
      clearTimeout(timer)
      finish(code ?? -1)
    })
  })
}

/**
 * Register the logon task for one launcher.
 *
 * Returns whether the task is now in place. A machine that forbids it (a locked
 * policy, a removed Task Scheduler) reports false and the caller falls back to a
 * hidden immediate launch rather than claiming the service is durable.
 */
export async function registerWindowsTask(launcherPath: string): Promise<boolean> {
  if (process.platform !== 'win32') return false
  return (await runSchtasks(registerTaskArgs(launcherPath))) === 0
}

/** Start the task now. The Task Scheduler owns the process from here. */
export async function runWindowsTask(): Promise<boolean> {
  if (process.platform !== 'win32') return false
  return (await runSchtasks(runTaskArgs())) === 0
}

/** Let the task run again at the next logon. */
export async function enableWindowsTask(): Promise<void> {
  if (process.platform !== 'win32') return
  await runSchtasks(enableTaskArgs())
}

/** Stop the service from coming back at logon until it is started again. */
export async function disableWindowsTask(): Promise<void> {
  if (process.platform !== 'win32') return
  await runSchtasks(disableTaskArgs())
}

/** Remove the task, for an uninstall. */
export async function deleteWindowsTask(): Promise<void> {
  if (process.platform !== 'win32') return
  await runSchtasks(deleteTaskArgs())
}
