/**
 * Remote-connection configuration.
 *
 * Every connection setting is read exclusively from public environment
 * variables. Missing values fall back to a documented localhost-only
 * development default — a production domain is never invented.
 *
 * The **LAN route is human-friendly by design**: it works out of the box with
 * zero configuration. The shared peer secret is auto-generated by the desktop
 * and delivered to the phone through the non-request URL fragment (`#pair=<secret>`), so
 * `PEER_SECRET_AUTH` is never required from the environment. The **cloud relay
 * is a deployment-time option**: in production it only activates when
 * `RELAY_URL`/`RELAY_TOKEN` (and MQTT credentials, when used) are actually
 * provisioned; otherwise the client silently stays LAN-only rather than error.
 *
 * The renderer bundle can only see `VITE_`-prefixed variables, so each key is
 * resolved from its canonical name first and a `VITE_`-prefixed variant second
 * (e.g. `RELAY_URL` then `VITE_RELAY_URL`). See `agent-out/config.md`.
 */

export const DEFAULT_LAN_PORT = 4455
export const DEFAULT_RELAY_URL = 'ws://localhost:8877'
export const DEFAULT_MQTT_URL = 'ws://localhost:8883'
export const DEFAULT_PWA_BASE_URL = 'http://localhost:5173'

export interface LanSettings {
  enabled: boolean
  port: number
  /** Loopback-only ws port for the desktop renderer's in-app connection. */
  localPort: number
  useMdns: boolean
  hosts: string[]
}

export interface RelayMqttSettings {
  url: string | null
  username: string | null
  password: string | null
}

export interface RelaySettings {
  enabled: boolean
  url: string
  token: string | null
  mqtt: RelayMqttSettings
}

export interface PeerSettings {
  authSecret: string | null
}

export interface RemoteConfig {
  lan: LanSettings
  relay: RelaySettings
  peer: PeerSettings
  pwaBaseUrl: string
  production: boolean
}

/** Loose environment shape: booleans and numbers are tolerated (Vite envs). */
export type RemoteConfigSource = Record<string, string | boolean | number | undefined>

/** Resolve the effective environment for the running platform. */
export function readRemoteEnv(): RemoteConfigSource {
  const meta = import.meta as unknown as { env?: RemoteConfigSource }
  if (meta.env && typeof meta.env === 'object') return meta.env
  return {}
}

/** Read a string variable by canonical name, with a VITE_-prefixed fallback. */
function envString(source: RemoteConfigSource, key: string): string | null {
  const value = source[key] ?? source[`VITE_${key}`]
  return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null
}

function envBool(source: RemoteConfigSource, key: string, fallback: boolean): boolean {
  const value = envString(source, key)
  if (value === null) return fallback
  return value === 'true' || value === '1' || value.toLowerCase() === 'yes'
}

function envInt(source: RemoteConfigSource, key: string, fallback: number): number {
  const value = envString(source, key)
  if (value === null) return fallback
  const parsed = Number.parseInt(value, 10)
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback
}

function envList(source: RemoteConfigSource, key: string, fallback: string[]): string[] {
  const value = envString(source, key)
  if (value === null) return fallback
  return value
    .split(',')
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0)
}

/** Whether the running build is a production build. */
export function isProductionSource(source: RemoteConfigSource): boolean {
  if (typeof source['PROD'] === 'boolean') return source['PROD']
  const prod = source['PROD'] ?? source['VITE_PROD']
  if (prod === 'true' || prod === '1') return true
  return envString(source, 'NODE_ENV') === 'production'
}

export interface BuildRemoteConfigOptions {
  production?: boolean
}

/**
 * Build validated connection settings from an environment source.
 *
 * The LAN route never throws: it works with zero configuration (the peer
 * secret is delivered via the QR pairing URL). The relay is a deployment-time
 * option — in production it stays enabled only when its credentials are
 * actually provisioned, and otherwise degrades to LAN-only.
 */
export function buildRemoteConfig(
  source: RemoteConfigSource,
  options: BuildRemoteConfigOptions = {}
): RemoteConfig {
  const production = options.production ?? isProductionSource(source)

  const relayEnabled = envBool(source, 'RELAY_ENABLED', true)
  const lanEnabled = envBool(source, 'LAN_ENABLED', true)
  const relayUrl = envString(source, 'RELAY_URL')
  const relayToken = envString(source, 'RELAY_TOKEN')

  const mqttUrl = envString(source, 'MQTT_URL') ?? (production ? null : DEFAULT_MQTT_URL)
  const mqttUsername = envString(source, 'MQTT_USERNAME')
  const mqttPassword = envString(source, 'MQTT_PASSWORD')

  // The old environment-token relay is development-only. Production uses the
  // same-origin account relay, whose per-device credentials are issued at
  // runtime and never compiled into the public renderer bundle.
  const relayProvisioned = relayUrl !== null && relayToken !== null
  const mqttProvisioned = mqttUrl === null || (mqttUsername !== null && mqttPassword !== null)
  const relayUsable = !production && (!relayProvisioned || mqttProvisioned)

  return {
    lan: {
      enabled: lanEnabled,
      port: envInt(source, 'LAN_PORT', DEFAULT_LAN_PORT),
      localPort: envInt(source, 'LAN_LOCAL_PORT', envInt(source, 'LAN_PORT', DEFAULT_LAN_PORT) + 1),
      useMdns: envBool(source, 'LAN_USE_MDNS', false),
      hosts: envList(source, 'LAN_HOSTS', ['localhost'])
    },
    relay: {
      enabled: relayEnabled && relayUsable,
      url: relayUrl ?? DEFAULT_RELAY_URL,
      token: relayToken,
      mqtt: {
        url: mqttUrl,
        username: mqttUsername,
        password: mqttPassword
      }
    },
    peer: {
      authSecret: production ? null : envString(source, 'PEER_SECRET_AUTH')
    },
    pwaBaseUrl: envString(source, 'PUBLIC_REMOTE_PWA_URL') ?? DEFAULT_PWA_BASE_URL,
    production
  }
}

/** Build settings from the platform environment with localhost-only fallbacks. */
export function loadRemoteConfig(options: BuildRemoteConfigOptions = {}): RemoteConfig {
  return buildRemoteConfig(readRemoteEnv(), options)
}
